config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present? && request.subdomain != %w( www )
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank? || request.subdomain == %w( www )
  end
end

Rails.application.routes.draw do
  
  constraints(SubdomainBlank) do
    resources :accounts, only: [:new, :create]
    root 'welcome#index'
    get 'welcome/pricing'
    get 'welcome/feature'
    get 'welcome/features'
    get 'welcome/about_us'
  end
 

  constraints(SubdomainPresent) do
    
    # app init
    match '/init', to: 'init#index', via: :get
    match '/app',  to: 'init#index', via: :get

    # just remember to delete public/index.html.
    root to: 'init#index', via: :get

    # load routes from external files
    dir = File.expand_path(__dir__)
    files = Dir.glob( "#{dir}/routes/*.rb" )
    files.each do |file|
      if Rails.configuration.cache_classes
        require file
      else
        load file
      end
    end
  
  end  
#  match '*a', to: 'errors#routing', via: %i[get post put delete]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=1024">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>ChaturBots : <%= Setting.get('product_name') %></title>
  <%= stylesheet_link_tag "application", :media => 'all' %>
  <%= stylesheet_link_tag "application-print", :media => 'print' %>
  <% if Rails.configuration.assets.debug %>
  <%= javascript_include_tag "application" %>
  <% else %>
  <%= javascript_include_tag "application", :defer => 'defer' %>
  <% end %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=1024">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <%= stylesheet_link_tag "welcome" %>

<title> ChaturBots AI HelpDesk </title>

<% if Rails.configuration.assets.debug %>
<%= javascript_include_tag "welcome" %>
<% else %>
<%= javascript_include_tag "welcome", :defer => 'defer' %>
<% end %>
<%= javascript_include_tag 'particles.min'%>
<%= javascript_include_tag 'typed'%>

  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |msg,name| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<%= image_tag "logo_nav.png" , :style => "width:45px; margin-top:10px; margin-right: 10px;" %>

<%= link_to "chaturbots"  , root_path , :class => "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item <%= active_helper(root_path) %>">
  <%= link_to "Home"  , root_path , :class => "nav-link" %>
      </li>
      <li class="nav-item <%= active_helper(welcome_features_path) %>">
      <%= link_to "Features"  , welcome_features_path , :class => "nav-link" %>
      </li>
      <li class="nav-item <%= active_helper(welcome_pricing_path) %>">
      <%= link_to "Pricing"  , welcome_pricing_path , :class => "nav-link" %>

      </li>

      <li class="nav-item <%= active_helper(new_account_path) %>">
      <%= link_to "Start Free Trial"  , new_account_path , :class => "nav-link" %>

      </li>
     
    </ul>
  </div>
</nav>



<%= yield %>


</body>
</html>